version: '2'

services:
  node:
    image: node:0.12
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - pgsql
      - redis
    links:
      - pgsql:db
      - redis:cache
    command: /bin/bash -c "npm install && npm install -g knex nodemon && npm run development"
  pgsql:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=todolist
      - POSTGRES_PASSWORD=todolist
      - POSTGRES_DB=todolist
  redis:
    image: redis:3.0
