FROM node:6
MAINTAINER El jayro
COPY ./ /usr/src/app
WORKDIR /usr/src/app
RUN ["npm","install"]
EXPOSE 3000
CMD ["mongod"]

# 
# build image : docker build -t jsalgado/expressapi_node:latest .
#
# publish: docker push jsalgado/nsnode:1.0
# 
